name: user_repository
description: "The repo that handle users"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
    
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.1.0
  firebase_core: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
